# Originally generated by ‘nixos-generate-config’, now hand-maintained.
# To refresh it, use `nixos-generate-config --show-hardware-config --no-filesystems`:
# a plain regeneration re-adds fileSystems/swapDevices, which collide with ./disko.nix.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # Filesystems, swap and resumeDevice come from ./disko.nix;
  # LUKS/TPM2/Secure Boot from ./secure-boot.nix.

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
