#!/usr/bin/env bash
set -euo pipefail

apply_profile() {
    local connector identity mode scale x y size output
    for connector in /sys/class/drm/card*-DP-1; do
        [[ -e "$connector/status" ]] || continue
        [[ $(cat "$connector/status") == connected ]] || continue
        identity=$(od -An -tx1 -j8 -N8 "$connector/edid" | tr -d ' \n') || return 1
        # EDID manufacturer, product and serial; Niri caches these across switches.
        case "$identity" in
            4c2d920d31515a5a) # Samsung S24D330 monitor
                mode='1920x1080@60.000' scale=1 x=0 y=180 size='[530,300]'
                ;;
            4c2d6771000e0001) # Samsung TV
                # 3840 / 3 = 1280 logical pixels; keep the right edge at DP-3's x=1920.
                mode='3840x2160@30.000' scale=3 x=640 y=0 size='[1110,620]'
                ;;
            '') return 1 ;; # EDID may not be ready at the first hotplug event.
            *) return 0 ;;
        esac

        output=$(niri msg --json outputs | jq '."DP-1"') || return 1
        # Wait for Niri to process the same hotplug before changing its config.
        jq -e --argjson size "$size" \
            '.physical_size == $size and .logical != null' <<< "$output" >/dev/null || return 1

        # Ignore duplicate events, including any generated by our own modeset.
        if jq -e --arg mode "$mode" --argjson scale "$scale" --argjson x "$x" --argjson y "$y" '
            .modes[.current_mode] as $current | ($mode | split("@")) as $requested |
            $requested[0] == "\($current.width)x\($current.height)" and
            $current.refresh_rate == ($requested[1] | tonumber * 1000) and
            .logical.scale == $scale and .logical.x == $x and .logical.y == $y
        ' <<< "$output" >/dev/null; then
            return 0
        fi

        niri msg output DP-1 mode "$mode" &&
            niri msg output DP-1 scale "$scale" &&
            niri msg output DP-1 position set -- "$x" "$y"
        return $?
    done
}

# Subscribe before the initial check; no continuous polling between hotplug events.
{
    printf 'startup\n'
    exec stdbuf -oL udevadm monitor --udev --subsystem-match=drm
} | while IFS= read -r event; do
    [[ "$event" == startup || "$event" =~ ^UDEV[[:space:]]+\[ ]] || continue
    for attempt in {1..20}; do
        sleep 0.25
        if apply_profile; then
            break
        fi
        if [[ "$attempt" == 20 ]]; then
            echo 'DP-1 profile did not settle after hotplug; waiting for the next event.' >&2
        fi
    done
done
