#!/bin/sh -e

echo "Applying darwin configuration for work..."
sudo WORK_EMAIL="${WORK_EMAIL:?Set WORK_EMAIL}" darwin-rebuild switch --impure --flake ".#${hostname}" "$@"
echo "Switch to new generation complete!"
