#!/bin/sh -e

shift 2>/dev/null || true

echo "Applying NixOS configuration for ${hostname}..."
sudo SSH_AUTH_SOCK=$SSH_AUTH_SOCK /run/current-system/sw/bin/nixos-rebuild switch --flake ".#${hostname}" "$@"
echo "Switch to new generation complete!"
