#!/bin/sh -e

echo "Cleaning up old system generations (keeping the 2 latest)..."
sudo nh clean all --keep 2 --keep-since 7d

echo "Cleaning up boot partition..."
sudo nixos-rebuild boot --flake ".#${hostname}" --install-bootloader

echo "Cleanup complete!"
df -h /boot
